spring:
   profiles:
      active:
        - dev
---
server:
  port: 7001
spring:
  profiles: dev
  security:
    user:
      name: admin
      password: enjoy
  application:
    name: microcloud-config-eureka-client